name: dicoding_story_flutter
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  image_picker: ^0.8.7+3
  fluttertoast: ^8.2.2
  path_provider: ^2.0.15
  cached_network_image: ^3.3.0
  flutter_dotenv: ^5.1.0
  go_router: ^12.0.0
  path: ^1.9.1
  google_maps_flutter: ^2.2.3
  geolocator: ^9.0.2
  geocoding: ^3.0.0
  json_annotation: ^4.7.0
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.3.2
  json_serializable: ^6.5.4
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
